/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File
import java.nio.charset.StandardCharsets


fun main() {
    
    // Force the console to use UTF‑8 output
    System.setProperty("stdout.encoding", "UTF-8")
    System.setProperty("stderr.encoding", "UTF-8")

    // Read all lines/words from the provided file
    val words = File("src/main/resources/eventyr.txt")
            .readLines(StandardCharsets.UTF_8)


    // Sort the words by their letters
    // Words that has anagrams of each other will have same key
    val anagramGroups = words.groupBy { word ->
        word.toCharArray().sorted().joinToString("")
    }

    // Keep word groups that contains two or more words
    val validGroups = anagramGroups.values
        .filter { it.size > 1 }

    //Write each anagram group as seperate lines
    validGroups.forEach {
        println(it.joinToString(" "))
    }
}
